#+ summary: Retrieves all the information about ILIAD FeaturesOfInterest
#+ description: NOTE! make sure response content type is application/json
#+ endpoint: https://www.foodie-cloud.org/sparql?default-graph-uri=http://w3id.org/iliad/dataaset/jf-pilot-sample
#+ tags:
#+   - json
#+ method: GET
#+ pagination: 100
#+ endpoint_in_url: False
#+ transform: {
#+   "description": "?info",
#+   "$anchor": "description",
#+   "value": {
#+     "@iot.id": "?id",
#+     coordinates:
#+        - "?lat_n",
#+        - "?long_n"
#+     },
#+   }

PREFIX iliad-api: <https://w3id.org/iliad/api>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX sosa:  <http://www.w3.org/ns/sosa/>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX wgs84:  <http://www.w3.org/2003/01/geo/wgs84_pos#>
PREFIX rdfs:  <http://www.w3.org/2000/01/rdf-schema#>
PREFIX dwc:  <http://rs.tdwg.org/dwc/terms/>
PREFIX geo: <http://www.opengis.net/ont/geosparql#>
PREFIX oim-jf:  <http://w3id.org/iliad/oim/jellyfish#>

SELECT DISTINCT ?info ?id ?lat_n ?long_n
WHERE {
    ?s a sosa:FeatureOfInterest ;
        a ?type ;
        wgs84:lat ?lat ;
        wgs84:long ?long .
        FILTER (?type != URI('http://www.w3.org/ns/sosa/FeatureOfInterest'))
    BIND ("OGC SensorThings API - FeaturesOfInterest" AS ?info)
    BIND (REPLACE(STR(?s), "^.*/([^/]*)$", "$1") as ?id)
    BIND (xsd:float(?lat) AS ?lat_n)
    BIND (xsd:float(?long) AS ?long_n)
}
ORDER BY ?id
